# Generated by Django 4.2.18 on 2025-03-30 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("artist", models.CharField(max_length=255)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("genre", models.CharField(blank=True, max_length=100)),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="cd_covers/"),
                ),
            ],
        ),
    ]
