# Generated by Django 4.2.18 on 2025-04-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rating_delete_cd"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_collection_public",
            field=models.BooleanField(default=True),
        ),
    ]
