# Generated by Django 4.2.18 on 2025-03-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="friends",
            field=models.ManyToManyField(blank=True, to="users.profile"),
        ),
    ]
