# Generated by Django 4.2.20 on 2025-04-09 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordstar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cd',
            name='unique_code',
            field=models.CharField(blank=True, editable=False, max_length=12, unique=True),
        ),
    ]
